# Generated by Django 4.1.2 on 2023-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
